title: Open Badges Criteria
description: Promoting coding skills
remote_theme: pmarsceill/just-the-docs
search_enabled: true
aux_links:
    "Edit on GitHub":
      - "https://github.com/rcl-coding/openbadges-criteria"
footer_content: "Copyright &copy; 2019 Ray Consulting Limited. Distributed by an <a href=\"https://github.com/rcladmin/Shopeneur/blob/master/LICENSE\">MIT license.</a>"
plugins:
  - jekyll-seo-tag